"""
Link to problem: https://www.freecodecamp.org/learn/daily-coding-challenge/2025-11-30

                                    AI Detector
Today's challenge is inspired by the release of ChatGPT on November 30, 2022.

Given a string of one or more sentences, determine if it was likely generated by AI using the following rules:

It contains two or more dashes (-).
It contains two or more sets of parenthesis (()). Text can be within the parenthesis.
It contains three or more words with 7 or more letters.
Words are separated by a single space and only consist of letters (A-Z). Don't include punctuation or other non-letters as part of a word.
If the given sentence meets any of the rules above, return "AI", otherwise, return "Human".
"""
from collections import Counter
def detect_ai(text):
    # Rule #1: text contains two or more dashes
    if text.count("-") >= 2:
        return "AI"
    # Rule #2: text contains two or more sets of parenthesis
    open_count = 0
    pair_count = 0
    for ch in text:
        if ch == "(":
            open_count += 1
        elif ch == ")" and open_count > 0:
            open_count -= 1
            pair_count += 1
            if pair_count >= 2:
                return "AI"
    # Rule #3: Words are separated by a single space and only consist of letters (A-Z)
    word_list = text.split()
    long_word_count = 0
    for word in word_list:
        curr = "".join(ch for ch in word if ch.isalpha())      
        if len(curr) >= 7:
            long_word_count +=1 
            if long_word_count >= 3:
                return "AI"
    return "Human"

print(detect_ai("The quick brown fox jumped over the lazy dog.")                 ) # should return "Human".
print(detect_ai("The hypersonic brown fox - jumped (over) the lazy dog.")        ) # should return "Human".
print(detect_ai("Yes - you're right! I made a mistake there - let me try again.")) # should return "AI".
print(detect_ai("The extraordinary students were studying vivaciously.")         ) # should return "AI".
print(detect_ai("The (excited) student was (coding) in the library.")            ) # should return "AI".